# Generated by Django 5.0 on 2024-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_images_product_product_images_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
